### ISSUE TITLE
~~Wrong version tag was pushed~~ (Not true, maintainer was confused)

### ISSUE THREAD

**Issue by djdv** [djdv/go-swatch#4]
@jaitaiwan ~~it seems you [published a `v0.1.1` tag](https://github.com/djdv/go-swatch/releases/tag/v0.1.1) which is behind the [`v0.1.0` tag](https://github.com/djdv/go-swatch/releases/tag/v1.0.0).~~

~~Someone's code is depending on the v0 API (advertising itself as the v1 API): https://github.com/sargon2/gobot/blob/c5bff55bb63e7e5ac6ea186f54ef5184735d2dba/go.mod#L9~~

~~Would you be willing to push a `v0.1.2` and do a module retraction for `v0.1.1`?
https://go.dev/doc/modules/gomod-ref#retract~~
Edit:
Disregard that, I got confused between `v0.1.0`, `v1.0.0`, and, `v0.1.1`. I think everything is as expected.
The license part below is still a minor issue though.
How silly. I think I need a patch for my eyes instead of the code. 🤡

---

Also GitHub's license detection is being tripped up, and if that's the case it's probably true for other tools that scan repos too.
This repo should be auto detected as "ISC" but is now being presented as "Other".
I think it's because the file is `LICENSE.md` and because of the way markdown handles line breaks, our names are [accidentally combined on the same line](https://github.com/djdv/go-swatch/blob/e7a7adaf95187cc807b23c8be55a3c828bec39f9/LICENSE.md). (I missed this during review)

Renaming it to `LICENSE.txt` would probably fix that.
I imagine you could just fork it and apply the rename and see if this button's label changes back to "ISC" in your fork.
![image](https://github.com/djdv/go-swatch/assets/13862850/fc1c8040-a7b1-47be-bc13-84807119dbeb)

CC: @sargon2
~~Since you're dependent on this I suppose you could use either the v0 tag or a specific commit, or migrate to the V1 API after the tags are fixed.~~
Edit:
I made a mistake on that. But you could also still update to the new v1 API if you like.
(；´∀｀)

**Comment by sargon2** [comment]
No worries, I'm just using it as a joke hook for a slack bot, it's not production.  I went ahead and updated to v1.0.0.

**Comment by jaitaiwan** [comment]
I’m also surprised because I haven’t pushed any tags on this repo 😅

**Comment by djdv** [comment]
Yeah that's strange.
Git has you listed as the author for the [`v0.1.1` tag](https://github.com/djdv/go-swatch/releases/tag/v0.1.1) but [GitHub's activity on the repo](https://github.com/djdv/go-swatch/activity) shows nothing.
Not sure how that synced but since it's October I suppose it could have been a @ghost. 😆

---

Regarding the license, GitHub is confused but it seems like [godoc recognizes it](https://pkg.go.dev/github.com/djdv/go-swatch).
I was worried it wouldn't which causes it to not display the docs sometimes.
Will likely push a commit later that just renames it to `LICENSE.txt` just to be safe, but probably doesn't require a bump to `1.0.1`, just for that.
